server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${db.host}:${db.port}/node-pipes
    username: postgres
    password: postgres
springdoc:
  version: '@springdoc.version@'
  enable-native-support: true
  swagger-ui:
    use-root-path: true

db:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
