server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/node-pipes
    username: postgres
    password: postgres
springdoc:
  version: '@springdoc.version@'
  enable-native-support: true
  swagger-ui:
    use-root-path: true
